
APP:
  PROJECT_ID: "go"
  WEB_BASE_URL: ""
  API_BASE_URL: ""
  RELEASE: false
  PORT: 8000

HTTP_SERVER:
  READ_TIMEOUT: 5s
  WRITE_TIMEOUT: 10s
  IDLE_TIMEOUT: 120s

SQL:
  POSTGRE_SQL:
    HOST: "localhost"
    PORT: 5432
    USERNAME: ""
    PASSWORD: ""
    DATABASE_NAME: ""
    DRIVER_NAME: "postgres"
    ENABLE: false
  MYSQL_SQL:
    HOST: "localhost"
    PORT: 3306
    USERNAME: ""
    PASSWORD: ""
    DATABASE_NAME: ""
    DRIVER_NAME: "mysql"
    ENABLE: false

MONGO:
  HOST: "localhost"
  PORT: 27017
  TIMEOUT: "5s"
  USERNAME: ""
  PASSWORD: ""
  DATABASE_NAME: ""
  ENABLE: false

REDIS:
  HOST: "localhost"
  PORT: 6379
  PASSWORD: ""
  ENABLE: false

SWAGGER:
  TITLE: "Go API Docs"
  DESCRIPTION: "Go API is application to project management about ..."
  VERSION: "1.0"
  HOST: "localhost:8000"
  BASE_URL: "/api/v1"
  ENABLE: true

JWT:
  SECRET_KEY: "project_jwt_secret"
  ACCESS:
    EXPIRE_TIME:
      DAY: 1
      HOUR: 0
      MINUTE: 0
  REFRESH:
    EXPIRE_TIME:
      DAY: 24
      HOUR: 0
      MINUTE: 0  